using System;

namespace Page226
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            //This is my non-static class that will contain most of my methods.
            //I instantiate it here.  This fulfills #2.
            NumberHandler numberHelp = new NumberHandler();
            
            //I request user input.
            Console.WriteLine("Would you provide me with a number?  Integers or decimals are fine.");
            
            //I assume user input is a float by default, then check if it is an int instead.
            float userInput = 0.0f;
            
            //This throws an exception if it's not a valid float.  It was autogenerated.
            userInput = float.Parse(Console.ReadLine() ?? throw new InvalidOperationException());
            
            //This is where I check if it is an integer.  All integers are divisible by 1.
            //But, you cannot take a float (i.e. 3.4) and modulus it by 1 and get a result of 0.
            if (userInput % 1 == 0)
            {
                //*Typecasting!*
                int userIntInput = (int) userInput;
                //Calls a method to divide the input by 2, fulfilling #3.
                numberHelp.HandleInputs(userIntInput, out int resultInt);
                //A static class that has one method is called.
                LazyWrite.Print(resultInt.ToString());
            }
            else
            {
                //Calls a method to divide the input by 2, fulfilling #3.
                numberHelp.HandleInputs(userInput, out float resultF);
                //A static class that has one method is called.
                LazyWrite.Print(resultF.ToString());
            }
            
        }
    }
    
}