// See https://aka.ms/new-console-template for more information

namespace _243_Abstract_Class;

public class Program
{
    public static void Main()
    {
        //#5  SUMMON THE EMPLOYEE
        //#3 of Polymorphism submission: create an instance of an object that uses the interface.
        Employee<string> e233 = new Employee<string>();
        //#5  NAME HIM Sample Student
        e233.FirstName = "Sample";
        e233.LastName = "Student";
        
        //#5 INVOKE HIM!  MAKE HIM SAY HIS NAME!
        e233.SayName();
        //#3 of Polymorphism submission.
        e233.Quit();
        
        //   ***
        
        // Now on to later assignments.
        // Operators submission page 255
        
        //First employee is generated by me.
        Employee<string> e01 = new Employee<string>();
        e01.FirstName = "Brute";
        e01.LastName = "Davis";
        e01.SetId(2345);
        
        //I ask for input from the user.  They generate an id for themselves.
        Console.WriteLine("You are a new employee.  Please enter 4 digits that will compose you id.");
        //I make it an int so it's a valid id.  I am not checking for invalid replies.
        int newId = Convert.ToInt16(Console.ReadLine());
        //This employee gets the new id.  My overloaded == applies to employees, so I need 2 to compare.
        Employee<string> e02 = new Employee<string>();
        e02.SetId(newId);
        
        //BEHOLD!  I compare them with ==
        if (e02 == e01)
        {
            Console.WriteLine("You are Brute Davis.");
        }
        else
        {
            Console.WriteLine("Who are you again?  Security! Security!!");
        }

        //Code requested to further demonstrate polymorphic behavior.
        IQuittable refersToEmployee = e02;
        refersToEmployee.Quit();

        
        //        * * * 
        
        //PARAMETERS SUBMISSION ASSIGNMENT
        //#3  Instantiate an employee with object type "string"
        Employee<string> e03 = new Employee<string>();
        List<string> things = new List<string>() { "salt", "pepper", "allspice", "cloves", "thyme" };
        e03.setThings(things);
        e03.FirstName = "Rodger";
        e03.LastName = "Borholt";
        
        //#4 Instantiate an employee with the object type "int"
        Employee<int> e04 = new Employee<int>();
        List<int> intSequence = new List<int>() { 2,3,5,7,11,13,17,19 };
        e04.setThings(intSequence);
        e04.FirstName = "Prime";
        e04.LastName = "Numberman";

        //A foreach loop for each employee that spits out their list's contents.
        foreach (string thing in e03.getThings())
        {
            Console.WriteLine(thing);
        }
        foreach (int num in e04.getThings())
        {
            Console.WriteLine(num);
        }
        Console.WriteLine("Above should be the list of spices and of prime numbers.");
    }
}

