// See https://aka.ms/new-console-template for more information

namespace _243_Abstract_Class;

public class Program
{
    public static void Main()
    {
        //#5  SUMMON THE EMPLOYEE
        //#3 of Polymorphism submission: create an instance of an object that uses the interface.
        Employee e233 = new Employee();
        //#5  NAME HIM Sample Student
        e233.firstName = "Sample";
        e233.lastName = "Student";
        
        //#5 INVOKE HIM!  MAKE HIM SAY HIS NAME!
        e233.SayName();
        //#3 of Polymorphism submission.
        e233.Quit();
        
        //   ***
        
        // Now on to later assignments.
        // Operators submission page 255
        
        //First employee is generated by me.
        Employee e01 = new Employee();
        e01.firstName = "Brute";
        e01.lastName = "Davis";
        e01.setId(2345);
        
        //I ask for input from the user.  They generate an id for themselves.
        Console.WriteLine("You are a new employee.  Please enter 4 digits that will compose you id.");
        //I make it an int so it's a valid id.  I am not checking for invalid replies.
        int newId = Convert.ToInt16(Console.ReadLine());
        //This employee gets the new id.  My overloaded == applies to employees, so I need 2 to compare.
        Employee e02 = new Employee();
        e02.setId(newId);
        
        //BEHOLD!  I compare them with ==
        if (e02 == e01)
        {
            Console.WriteLine("You are Brute Davis.");
        }
        else
        {
            Console.WriteLine("Who are you again?  Security! Security!!");
        }

        //Code requested to further demonstrate polymorphic behavior.
        IQuittable refersToEmployee = e02;
        refersToEmployee.Quit();


    }
}

